name: Deploy to Back4App on Release

on:
  push:
      branches: [ main ]
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Back4App CLI
        run: |
          curl https://raw.githubusercontent.com/back4app/parse-cli/back4app/installer.sh | sudo /bin/bash

      - name: Configure .parse files
        env:
          B4A_APP_ID: ${{ secrets.B4A_APP_ID }}
          B4A_EMAIL: ${{ secrets.B4A_EMAIL }}
        run: |
          # Arquivo .parse.local
          echo '{
            "applications": {
              "_default": { "link": "setup-b4a" },
              "setup-b4a": { "applicationId": "'"$B4A_APP_ID"'" }
            }
          }' > .parse.local

          # Arquivo .parse.project
          echo '{
            "project_type": 1,
            "parse": { "jssdk": "2.2.25" },
            "email": "'"$B4A_EMAIL"'"
          }' > .parse.project

          # Verificação (opcional)
          cat .parse.local
          cat .parse.project

      - name: Configure Back4App Account Key
        run: echo "${{ secrets.B4A_ACCOUNT_KEY }}" | b4a configure accountkey

      - name: Select Back4App App
        run: b4a select "${{ secrets.B4A_APP_ID }}"

      - name: Build React App
        run: |
          cd client
          npm install
          npm run build
          mv dist ../public

      - name: Deploy to Back4App
        run: b4a deploy